# Generated by Django 5.2 on 2025-04-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Resipe',
        ),
    ]
