# Generated by Django 5.2 on 2025-04-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
